# exercicio 1
SELECT MAX(SALARY) FROM hr.employees;

# exercicio 2
SELECT MAX(SALARY) - MIN(SALARY) FROM hr.employees;

# exercicio 3
SELECT JOB_ID, AVG(SALARY) AS AVERAGE FROM hr.employees GROUP BY JOB_ID ORDER BY AVERAGE DESC;

# exercicio 4
SELECT SUM(SALARY) FROM hr.employees;

# exercicio 5
SELECT ROUND(MAX(SALARY), 2), ROUND(MIN(SALARY), 2), ROUND(SUM(SALARY), 2), ROUND(AVG(SALARY), 2) FROM hr.employees;

# exercicio 6
SELECT COUNT(*) FROM hr.employees WHERE JOB_ID = 'IT_PROG';

# exercicio 7
SELECT JOB_ID, SUM(SALARY) FROM hr.employees GROUP BY JOB_ID;

# exercicio 8
SELECT JOB_ID, SUM(SALARY) FROM hr.employees GROUP BY JOB_ID HAVING JOB_ID = 'IT_PROG';

# exercicio 9
SELECT JOB_ID, AVG(SALARY) AS AVERAGE FROM hr.employees GROUP BY JOB_ID HAVING JOB_ID <> 'IT_PROG' ORDER BY AVERAGE DESC;

# exercicio 10
SELECT DEPARTMENT_ID, AVG(SALARY) AS AVERAGE, COUNT(*) AS FUNC FROM hr.employees GROUP BY DEPARTMENT_ID HAVING FUNC > 10;

# exercicio 11
SET SQL_SAFE_UPDATES = 0;
UPDATE hr.employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';

# exercicio 12
SELECT * FROM hr.employees WHERE CHAR_LENGTH(FIRST_NAME) >= 8;

# exercicio 13
SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;

# exercicio 14
SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;

# exercicio 15
SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;

# exercicio 16
SELECT UCASE(CONCAT(FIRST_NAME, ' ', LAST_NAME)) AS NAME FROM hr.employees;

# exercicio 17
SELECT LAST_NAME, HIRE_DATE FROM hr.employees WHERE MONTH(HIRE_DATE) = '07' AND YEAR(HIRE_DATE) = '1987';

# exercicio 18
SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) AS TIME FROM hr.employees;