"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var evaluationResult_1 = require("./evaluationResult");
var exam_1 = require("./exam");
var student_1 = require("./student");
var subject_1 = require("./subject");
var teacher_1 = require("./teacher");
var work_1 = require("./work");
var carolina = new student_1.default('Carolina da Silva', new Date('2005/03/17'));
var lucas = new student_1.default('Lucas Peixoto Salgueiro', new Date('2006/07/19'));
var math = new subject_1.default('Matemática');
var history = new subject_1.default('História');
var marta = new teacher_1.default('Marta da Silva', new Date('1980/03/30'), 2000, math);
var joao = new teacher_1.default('João Antônio da Costa', new Date('1982/04/21'), 2000, history);
var examMath = new exam_1.default(marta, 25);
var workMath = new work_1.default(marta, 50);
var examHistory = new exam_1.default(joao, 25);
var workHistory = new work_1.default(joao, 50);
carolina.addEvaluationResult(new evaluationResult_1.default(examMath, 23));
carolina.addEvaluationResult(new evaluationResult_1.default(workMath, 42));
carolina.addEvaluationResult(new evaluationResult_1.default(examHistory, 25));
carolina.addEvaluationResult(new evaluationResult_1.default(workHistory, 50));
console.log('Avaliações: ', carolina.evaluationsResults);
console.log('Soma das notas: ', carolina.sumGrades());
console.log('Média das notas: ', carolina.sumAverageGrades());
lucas.addEvaluationResult(new evaluationResult_1.default(examMath, 25));
lucas.addEvaluationResult(new evaluationResult_1.default(workMath, 49));
lucas.addEvaluationResult(new evaluationResult_1.default(examHistory, 20));
lucas.addEvaluationResult(new evaluationResult_1.default(workHistory, 50));
console.log('Avaliações: ', lucas.evaluationsResults);
console.log('Soma das notas: ', lucas.sumGrades());
console.log('Média das notas: ', lucas.sumAverageGrades());
